// Generates the macOS PF ruleset text for the app's private anchor —
// Automation Architecture guide §4.8/§6: rules are generated from the FULL
// current desired state and syntax-checked (pfctl -nf, via privilegedOps.js)
// before replacing anything, never appended incrementally.
//
// Every field that ends up inside the rule text is strictly validated
// first (interface name / IPv4 shape) and rejected outright otherwise —
// this is the actual rule-injection boundary: `pfctl -nf` faithfully
// parses whatever text this function returns, so a device record with a
// stray "\n" or shell-looking value in its `usbIp`/`tunIface` must never
// reach the ruleset. No caller-controlled string is ever accepted as-is.

const IFACE_RE = /^[a-zA-Z0-9._-]{1,15}$/; // BSD IFNAMSIZ is 16 incl. NUL
const IPV4_RE = /^(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}$/;

function assertIface(value, label) {
  if (typeof value !== "string" || !IFACE_RE.test(value)) {
    throw new Error(`${label} must be a valid interface name, got: ${JSON.stringify(value)}`);
  }
  return value;
}

function assertIpv4(value, label) {
  if (typeof value !== "string" || !IPV4_RE.test(value)) {
    throw new Error(`${label} must be a valid IPv4 address, got: ${JSON.stringify(value)}`);
  }
  return value;
}

// One device's routed pass rules + its own non-DNS-UDP block, matching the
// guide's exact working grammar for the validated HTTP-proxy/virtual-DNS
// topology (§4.8: "the validated macOS PF grammar required the explicit
// peer in route-to").
function deviceRules(bridgeIface, device) {
  const usbIp = assertIpv4(device.usbIp, "device.usbIp");
  const tunIface = assertIface(device.tunIface, "device.tunIface");
  const tunPeer = assertIpv4(device.tunPeer, "device.tunPeer");
  const routeTo = `(${tunIface} ${tunPeer})`;
  return [
    `pass in quick on ${bridgeIface} route-to ${routeTo} inet proto tcp from ${usbIp} to any keep state`,
    `pass in quick on ${bridgeIface} route-to ${routeTo} inet proto udp from ${usbIp} to any port 53 keep state`,
    `block in quick on ${bridgeIface} inet proto udp from ${usbIp} to any`,
  ];
}

// `devices`: one entry per currently-routed device — Architecture guide §6
// step 5j: "regenerate PF rules for all active devices atomically". A
// device with no tunnel yet (not proxy-routed) simply has no entry here;
// omitting it is what actually removes its rule on the next reload, since
// this always replaces the whole anchor rather than patching it.
export function generatePfRuleset({ bridgeIface, devices = [], blockedIps = [], blockIpv6 = true } = {}) {
  assertIface(bridgeIface, "bridgeIface");
  if (!Array.isArray(devices)) throw new Error("devices must be an array");
  if (!Array.isArray(blockedIps)) throw new Error("blockedIps must be an array");

  const seenIps = new Set();
  const lines = ["# Generated by phone-farm-control — do not hand-edit, replaced on every routing change."];
  for (const device of devices) {
    if (seenIps.has(device.usbIp)) throw new Error(`duplicate usbIp in desired state: ${device.usbIp}`);
    seenIps.add(device.usbIp);
    lines.push(...deviceRules(bridgeIface, device));
  }
  for (const blockedIp of blockedIps) {
    const usbIp = assertIpv4(blockedIp, "blockedIp");
    if (seenIps.has(usbIp)) throw new Error(`usbIp cannot be both routed and blocked: ${usbIp}`);
    seenIps.add(usbIp);
    lines.push(`block in quick on ${bridgeIface} inet from ${usbIp} to any`);
  }
  if (blockIpv6) lines.push(`block in quick on ${bridgeIface} inet6 all`);
  return `${lines.join("\n")}\n`;
}

// Parses `pfctl -vvs rules` output (privilegedOps.js's inspectRules()) for
// health-checking (Automation Architecture guide §4.10: "generated device
// rule is loaded and packet counters increase after traffic"). Each rule
// line is followed by a stats line shaped like:
//   [ Evaluations: 42       Packets: 15         Bytes: 1024        States: 1 ]
// Sums packets per usbIp across that device's several rules (tcp pass, udp
// pass, udp block). A usbIp with no entry in the result means its rule is
// no longer loaded — the orchestrator's own health check treats that as
// "route lost", not as "traffic is merely idle right now".
const RULE_IP_RE = /\bfrom\s+(\d{1,3}(?:\.\d{1,3}){3})\s+to\s+any\b/;
const COUNTER_RE = /Packets:\s*(\d+)/;

export function parsePfCounters(inspectOutput) {
  const totals = new Map(); // usbIp -> summed packets
  let pendingIp = null;
  for (const line of String(inspectOutput || "").split(/\r?\n/)) {
    const ruleMatch = RULE_IP_RE.exec(line);
    if (ruleMatch) { pendingIp = ruleMatch[1]; continue; }
    const counterMatch = COUNTER_RE.exec(line);
    if (counterMatch && pendingIp) {
      const packets = Number.parseInt(counterMatch[1], 10);
      totals.set(pendingIp, (totals.get(pendingIp) ?? 0) + packets);
      pendingIp = null; // exactly one stats line follows each rule line
    }
  }
  return [...totals.entries()].map(([usbIp, packets]) => ({ usbIp, packets }));
}

export { IFACE_RE, IPV4_RE };
