import { test } from "node:test";
import assert from "node:assert/strict";
import { generatePfRuleset, parsePfCounters } from "../../src/pfRuleGenerator.js";

const ONE_DEVICE = { usbIp: "192.168.2.10", tunIface: "utun7", tunPeer: "10.0.0.1" };

// A real `pfctl -vvs rules` output shape for one device's three rules
// (tcp pass, udp pass, udp block) plus a second device's tcp pass.
const INSPECT_SAMPLE = [
  "@1 pass in quick on bridge0 route-to (utun7 10.0.0.1) inet proto tcp from 192.168.2.10 to any flags S/SA keep state",
  "  [ Evaluations: 42       Packets: 15         Bytes: 1024          States: 1     ]",
  "@2 pass in quick on bridge0 route-to (utun7 10.0.0.1) inet proto udp from 192.168.2.10 to any port = 53 keep state",
  "  [ Evaluations: 10       Packets: 5          Bytes: 512           States: 0     ]",
  "@3 block in quick on bridge0 inet proto udp from 192.168.2.10 to any",
  "  [ Evaluations: 3        Packets: 0          Bytes: 0             States: 0     ]",
  "@4 pass in quick on bridge0 route-to (utun8 10.0.0.3) inet proto tcp from 192.168.2.11 to any flags S/SA keep state",
  "  [ Evaluations: 7        Packets: 100        Bytes: 8192          States: 1     ]",
].join("\n");

test("generates the exact validated grammar for one device, plus the IPv6 block", () => {
  const rules = generatePfRuleset({ bridgeIface: "bridge0", devices: [ONE_DEVICE] });
  assert.equal(rules, [
    "# Generated by phone-farm-control — do not hand-edit, replaced on every routing change.",
    "pass in quick on bridge0 route-to (utun7 10.0.0.1) inet proto tcp from 192.168.2.10 to any keep state",
    "pass in quick on bridge0 route-to (utun7 10.0.0.1) inet proto udp from 192.168.2.10 to any port 53 keep state",
    "block in quick on bridge0 inet proto udp from 192.168.2.10 to any",
    "block in quick on bridge0 inet6 all",
    "",
  ].join("\n"));
});

test("blockIpv6: false omits the inet6 block line", () => {
  const rules = generatePfRuleset({ bridgeIface: "bridge0", devices: [ONE_DEVICE], blockIpv6: false });
  assert.equal(rules.includes("inet6"), false);
});

test("an empty device list still produces a valid (empty-of-device-rules) ruleset", () => {
  const rules = generatePfRuleset({ bridgeIface: "bridge0", devices: [] });
  assert.match(rules, /^# Generated/);
  assert.equal(rules.includes("route-to"), false);
});

test("regenerating with fewer devices drops the missing device's rules entirely (full-replace, not append)", () => {
  const two = generatePfRuleset({ bridgeIface: "bridge0", devices: [ONE_DEVICE, { usbIp: "192.168.2.11", tunIface: "utun8", tunPeer: "10.0.0.2" }] });
  assert.equal((two.match(/route-to/g) || []).length, 4);
  const one = generatePfRuleset({ bridgeIface: "bridge0", devices: [ONE_DEVICE] });
  assert.equal((one.match(/route-to/g) || []).length, 2);
  assert.equal(one.includes("192.168.2.11"), false);
});

test("rejects a duplicate usbIp across two device entries", () => {
  assert.throws(
    () => generatePfRuleset({ bridgeIface: "bridge0", devices: [ONE_DEVICE, { ...ONE_DEVICE, tunIface: "utun9" }] }),
    /duplicate usbIp/
  );
});

test("rejects an invalid bridge interface name", () => {
  assert.throws(() => generatePfRuleset({ bridgeIface: "not a shell; rm -rf /", devices: [] }), /valid interface name/);
  assert.throws(() => generatePfRuleset({ bridgeIface: "", devices: [] }), /valid interface name/);
});

test("rejects injection attempts through usbIp — a newline can never smuggle an extra rule", () => {
  const malicious = { usbIp: "1.2.3.4\npass in quick on bridge0 route-to (utun0 10.0.0.1) inet proto tcp from any to any keep state", tunIface: "utun7", tunPeer: "10.0.0.1" };
  assert.throws(() => generatePfRuleset({ bridgeIface: "bridge0", devices: [malicious] }), /valid IPv4 address/);
});

test("rejects injection attempts through tunIface", () => {
  const malicious = { usbIp: "192.168.2.10", tunIface: "utun7\nblock in quick on bridge0 all", tunPeer: "10.0.0.1" };
  assert.throws(() => generatePfRuleset({ bridgeIface: "bridge0", devices: [malicious] }), /valid interface name/);
});

test("rejects an out-of-range IPv4 octet", () => {
  const bad = { usbIp: "192.168.2.999", tunIface: "utun7", tunPeer: "10.0.0.1" };
  assert.throws(() => generatePfRuleset({ bridgeIface: "bridge0", devices: [bad] }), /valid IPv4 address/);
});

test("rejects a tunIface longer than BSD's interface name limit", () => {
  const bad = { usbIp: "192.168.2.10", tunIface: "a".repeat(20), tunPeer: "10.0.0.1" };
  assert.throws(() => generatePfRuleset({ bridgeIface: "bridge0", devices: [bad] }), /valid interface name/);
});

test("rejects a non-array devices argument", () => {
  assert.throws(() => generatePfRuleset({ bridgeIface: "bridge0", devices: "not-an-array" }), /devices must be an array/);
});

test("parsePfCounters sums packets across a device's several rules", () => {
  const counters = parsePfCounters(INSPECT_SAMPLE);
  assert.deepEqual(
    counters.sort((a, b) => a.usbIp.localeCompare(b.usbIp)),
    [{ usbIp: "192.168.2.10", packets: 20 }, { usbIp: "192.168.2.11", packets: 100 }]
  );
});

test("parsePfCounters returns an empty array for an anchor with no rules loaded", () => {
  assert.deepEqual(parsePfCounters(""), []);
  assert.deepEqual(parsePfCounters("No ALTQ support in kernel\n"), []);
});

test("parsePfCounters ignores a rule line with no matching stats line", () => {
  const output = "@1 pass in quick on bridge0 inet proto tcp from 192.168.2.10 to any keep state\n";
  assert.deepEqual(parsePfCounters(output), []);
});
